services:
  db:
    image: postgres:13
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_NAME}
    ports:
      - "5432:5432"
    networks:
      - container_localnet

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - container_localnet

networks:
  container_localnet:
    external: true