from dotenv import load_dotenv
from os import getenv
from datetime import timedelta


load_dotenv()


API_KEY_CURRENCY = getenv('API_KEY_CURRENCY')
EXTERNAL_CURRENCY_URL_ROUTE = getenv('EXTERNAL_CURRENCY_URL_ROUTE')
EXTERNAL_CONVERT_CURRENCY_URL_ROUTE = getenv('EXTERNAL_CONVERT_CURRENCY_URL_ROUTE')

SECRET_KEY = getenv('SECRET_KEY')
ALGORITHM = getenv('ALGORITHM')
EXPIRATION_TIME = timedelta(seconds=300)

POSTGRESQL_USER = getenv('POSTGRESQL_USER')
POSTGRESQL_DATABASE = getenv('POSTGRESQL_NAME')
POSTGRESQL_PASSWORD = getenv('POSTGRESQL_PASSWORD')

POSTGRESQL_HOST = getenv('POSTGRESQL_HOST', 'host.docker.internal')
POSTGRESQL_PORT = int(getenv('POSTGRESQL_PORT', 5432))
POSTGRESQL_MAX_CONNECTIONS = int(getenv('POSTGRESQL_MAX_CONNECTIONS', '2'))


POSTGRES_STR_FOR_CONNECT = f'postgresql+asyncpg://{POSTGRESQL_USER}:{POSTGRESQL_PASSWORD}@{POSTGRESQL_HOST}:{POSTGRESQL_PORT}/{POSTGRESQL_DATABASE}'
